### PR TITLE
Use neovim socket functions instead of vimproc

### LINKED ISSUE #211: Setting up dictionary on neovim/vim
I have recently started to learn Japanese and I am a heavy vim user. I really like this plugin, which I discovered accidentally and I can already use this to type in hiragana and katakana. Thanks!

However, I am struggling to find information on how to setup the functionality to use a dictionary. I am happy to create a PR for some English documentation, but would love to know how to get the suggestions for kanji working.

The most recent thing that I have tried:
```
$ sudo pacman -S skk-jisyo
$ docker run -d -p 127.0.0.1:1178:1178 uyorum/skkserv-google
```
And add the following to my neovim `init.vim`:
```
    let g:eskk#dictionary = {'path': "~/.local/share/nvim/skk-jisyo"}

    " Use skkserv-google
    " (https://github.com/uyorum/go-skkserv-google)
    let g:eskk#server = {
    \   'host': '127.0.0.1',
    \   'port': 1178,
    \}
```

Do I understand correctly that the server may not work because I am not using `vim` or `vimproc`? Would there be interest in supporting `neovim`? Am I missing anything obvious? What is the shortcut to trigger the completions?

### PR DESCRIPTION
**Pull request by Shougo**
Fix #211

### CODE REVIEW

**Comment by aignas** [comment]
Thanks for coding this up. How do I debug why I am not getting the completion? Does this work with `deoplete.nvim`?

I have the following in my `init.vim`:
```
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1

" ...
let g:eskk#server = {
\   'host': '127.0.0.1',
\   'port': 1178,
\}
```

and I have started the skk server via:
```
docker run -d -p 127.0.0.1:1178:1178 uyorum/skkserv-google
```

**Comment by Shougo** [comment]
I have tested the branch and it works for me.
I will merge it soon.

**Comment by Shougo** [comment]
> Thanks for coding this up. How do I debug why I am not getting the completion? Does this work with deoplete.nvim?

It works, but you must install large dictionary to get completion.
Because skk server does not support any of completion.  It is skk server protocol feature.

Please install SKK-JISYO.L and configure like this.

```vim
  let g:eskk#large_dictionary = {
        \   'path': '/usr/share/skk/SKK-JISYO.L',
        \   'sorted': 1,
        \   'encoding': 'euc-jp',
        \}
```

**Comment by ress997** [comment]
LGTM

**Comment by aignas** [comment]
I am still having trouble at setting this up in `nvim`.

I'm getting the following error message:
```
[/var/folders/53/13ph1xvn54scddtb7l6v38j40000gn/T/nvimnYUezm/0] [Sat Apr  6 16:05:29 2019] [WARN] internal error: Preedit.get_begin_col() current phase is "0", but it must not be called in normal phase.
```

My `init.vim` is:
```
let s:data_dir = $HOME . '/.local/share/nvim'

call plug#begin(s:data_dir . '/plugged')
Plug 'tyru/eskk.vim', { 'branch': 'neovim' }
call plug#end()

let g:eskk#directory = s:data_dir . '/skk'
let g:eskk#log_file_level = 3
let g:eskk#log_cmd_level = 2
let g:eskk#start_completion_length = 1
let g:eskk#dictionary = {
    \   'path': s:data_dir . '/skk/skk-jisyo.s',
    \   'sorted': 0,
    \   'encoding': 'utf-8',
    \}
let g:eskk#large_dictionary = {
    \   'path': s:data_dir . '/skk/SKK-JISYO.L',
    \   'sorted': 1,
    \   'encoding': 'euc-jp',
    \}
```

I open some file with `nvim test.md` and then use `Ctrl-X Ctrl-O` in order to attempt to convert hiragana to kanji, however, I don't get any dialogues or anything, except the error message.

**Comment by aignas** [comment]
Thank you very much, I have finally realized that I was trying to use the plugin in a wrong way.

For any other new learners, I have summarized some notes [here](https://vi.stackexchange.com/a/15342/16484). I hope to add some docs as a PR a bit later on.

Thanks again for your help!

**Pull request merged**
